//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteDbExplorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStartPageOnOpen {
            get {
                return ((bool)(this["ShowStartPageOnOpen"]));
            }
            set {
                this["ShowStartPageOnOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStartOnCloseAll {
            get {
                return ((bool)(this["ShowStartOnCloseAll"]));
            }
            set {
                this["ShowStartOnCloseAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horizontal")]
        public global::System.Windows.Controls.Orientation CollectionExplorer_SplitOrientation {
            get {
                return ((global::System.Windows.Controls.Orientation)(this["CollectionExplorer_SplitOrientation"]));
            }
            set {
                this["CollectionExplorer_SplitOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CollectionExplorer_ShowPreview {
            get {
                return ((bool)(this["CollectionExplorer_ShowPreview"]));
            }
            set {
                this["CollectionExplorer_ShowPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int CollectionExplorer_ContentMaxLength {
            get {
                return ((int)(this["CollectionExplorer_ContentMaxLength"]));
            }
            set {
                this["CollectionExplorer_ContentMaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EditDocument")]
        public global::LiteDbExplorer.Modules.DbCollection.CollectionItemDoubleClickAction CollectionExplorer_DoubleClickAction {
            get {
                return ((global::LiteDbExplorer.Modules.DbCollection.CollectionItemDoubleClickAction)(this["CollectionExplorer_DoubleClickAction"]));
            }
            set {
                this["CollectionExplorer_DoubleClickAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vertical")]
        public global::System.Windows.Controls.Orientation DocumentPreview_SplitOrientation {
            get {
                return ((global::System.Windows.Controls.Orientation)(this["DocumentPreview_SplitOrientation"]));
            }
            set {
                this["DocumentPreview_SplitOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int DocumentPreview_ContentMaxLength {
            get {
                return ((int)(this["DocumentPreview_ContentMaxLength"]));
            }
            set {
                this["DocumentPreview_ContentMaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<System.DateTime> UpdateManager_LastCheck {
            get {
                return ((global::System.Nullable<System.DateTime>)(this["UpdateManager_LastCheck"]));
            }
            set {
                this["UpdateManager_LastCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Version UpdateManager_LastVersion {
            get {
                return ((global::System.Version)(this["UpdateManager_LastVersion"]));
            }
            set {
                this["UpdateManager_LastVersion"] = value;
            }
        }
    }
}
